//Primeira Aula - Tipo Number 
/*const primeiroNumero = 4;
const segundoNumero = 2;

const operaçãoMatematica = primeiroNumero + segundoNumero;

console.log(operaçãoMatematica);*/

// ponto fluante

/*const mate = 0.45; 
const segundoMate = 0.30;

const novaoperaçao = mate / segundoMate;
 console.log(novaoperaçao);*/

 /*const allua = waltinho;
 const segundaallua = 10;
const  resultado =(allua + segundaallua);
console.log(resultado);*/

var a = 10
var b = 0
//console.log(a/b) 
// function do  salario do walter




function ganhoPorHora(salario, horasTrabalhadasNoMes) {
    const salarioHora = (salario / horasTrabalhadasNoMes); 
    return salarioHora;
}

function ganhoPorHora1(salario, horasTrabalhadasNoMes) {
    const salarioHora1 = (salario / horasTrabalhadasNoMes); 
    return Math.round(salarioHora1);
}

console.log(ganhoPorHora(3000,176));
console.log(ganhoPorHora1(3000,176));





