//Tipo String

const texto1 = "Olá, Mundão";
const texto2 = "irei usar essa senha";
const stringdeNumero = 'Wasenha123' ; 

const citação = 'ola mundo , "oi"';
//console.log(citação);

const vida = 'frase do waltinho "sai da minha bota!"';
//console.log(vida);

//concatenação
const texto01 = "meu nome é "
const textto = " Alexsandra"

//console.log(texto01 + textto);


const cifrao = '\u0024'
const aMaiusculo = '\u0041'
const tique = '\u2705'
const hiragana = '\u3041'
const coracao = '\u2665';

//console.log(coracao);
//console.log(aMaiusculo)
//console.log(tique)
//console.log(hiragana)

const cidade = "belo horizonte";
const input = "Belo Horizonte";

//console.log(cidade === input); // false

// Para contar quantos caracteres usa o length 

const senha = "minhaSenha123"
console.log(senha.length) // 13 caracteres

const novo = '\f'
const Pnew = novo
const pold = Pnew

console.log(novo);
console.log('\f');
console.log(pold)




