// lopps
// for é um comando  que executa x vezes uma açao seguindo  a forma  como foi definido pra ele  faze la 


for (let i = 0; i < 10; i=i+1){
    //console.log(i);
}

for (let a = 45; a < 110; a=a+1){
   console.log(a);
}

 // com strig (lista) - é otimo para ler  vetores 
let lista = ["cachorro", "gato",  "galinha" ];
for (let i = 0; i < lista.length; i++){
   // console.log(lista[i]);
}

let valores  = [1,2,3,4,5,];

for (let i = 0; i < valores.length; i++){
    valores[i] = valores[i] * 2;
    console.log(valores[i]);
}

//exemplos
let i = 5 
for (; i < 10; i++){
    //console.log(i);
}

