// if (se) é um comando que permite executar o codigo apenas se a condiçao entre parenteses for verdadeira - true 
 // else (se não for)
// else if (se não se )


let x = 2 ;
if (x == 2 ) { 
    
}
console.log(); 
let disponivel = true; 
let quantidade = 5;

if (quantidade > 0 && disponivel){
    console.log("Produto disponivel para venda ");
}

let novotest = true;
let novoteste = 80;
 if (novoteste > 120 && novotest) {
     console.log("E é isso ");
 } else {
     console.log("não é isso");
 }

let cidade = "Ferraz de vasconcelos"

if (cidade == "São paulo") {
    console.log("opa!");
} 
else if (cidade == "Rio de Janeiro"){
    console.log("eita!");
}
else if (cidade == "Porto Alegre"){
    console.log( "oba");
} else { 
    console.log("cancela");
}
